# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
markdown:         kramdown
highlighter:      rouge # changed from `pygments` as github says so

# Setup
title:               Leap Of Code
tagline:             'by Vivek Saxena'
description:         'A landing page for everything front-end and a personal blog.'
url:                 http://www.leapofcode.com
baseurl:             ''
gems: [jekyll-paginate]
paginate: 3

# About/contact
author:
  name:              Vivek Saena
  url:               leapofcode.com
  email:             vivek77saxena@gmail.com
  github:            vivek77saxena
  twitter:           vivek77saxena
  linkedin:          vivek77saxena
  goodreads:         vivek77saxena

# Custom vars
version:             1.0.0

